name: Deploy to github pages

on:
  workflow_dispatch: # enables on-demand/manual triggering
  push:
    branches:    
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # We will deploy with only one version of node  

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        shell: bash
        run: |
          npm ci        
          npm run lint
          npm run build --if-present
          npm run export
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
